### ISSUE TITLE
Dockerfile issue

### ISSUE THREAD

**Issue by ahjohannessen** [nordic-institute/X-Road-Security-Server-toolkit#56]
When I try to build a docker image as specified in the readme, I get this:

```
Building wheel for jq (PEP 517): finished with status 'error'
```

**Comment by bertvi** [comment]
Installation using the Dockerfile was introduced in older versions of the X-Road Security Server Toolkit and it was decided not to update and keep that option for installation. The Dockerfile and the respective Makefile target have now been removed.
